name: Publish Mod

# Run when a new release is... released
on: 
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      # Use checkout to publish the files in your repo
      - uses: actions/checkout@v3
      - uses: GreenTF/upload-thunderstore-package@v4.2
        with:
          namespace: Moonheim
          description: Test 
          token: ${{ secrets.THUNDERSTORE_API_TOKEN }}
          name: MoonheimModpack
          version: ${{ github.ref_name }}
          community: Valheim
          repo: valheim.thunderstore.io
          categories: |
            hildirs-request-update
            modpacks
